### ISSUE TITLE
The application does not move

### ISSUE THREAD

**Issue by rauleb** [stonesam92/ChitChat#59] opened 2015-09-01 12:30 UTC
I have the beta of "The Captain" and my application is fixed in the middle of the screen, I can not move.
I do not know, if this happens only with my operating system

**Comment by LucaTNT** [comment] 2015-09-02 17:59
Same here, on the latest Developer Beta of El Capitan.
I'm currently dragging the corners of the window to use window resizing as a poor man's move command, but it's definitely not a great solution.

**Comment by markimarc** [comment] 2015-09-03 17:29
Same here, also on the latest Developer Beta.

**Comment by vmax77** [comment] 2015-09-04 07:49
In Public Beta and same issue!

**Comment by zvaehn** [comment] 2015-09-06 16:02
same here. Did you guys concider that it is an OSX Bug and not a bug of the app itself?

**Comment by LucaTNT** [comment] 2015-09-06 16:33
Yes, but I thought it was worth reporting as it might be due to a change in El Cap rather than a simple bug in it.

**Comment by alexBethke** [comment] 2015-09-06 16:46
Same here with El Capitan Beta Version 10.11 Beta 15A278b. My guess is the title bar is missing in the ChitChat Window. Haven't figured out how to fix this though

**Comment by zvaehn** [comment] 2015-09-06 16:47
I know how to move it once :D
Try to open another window, drag it beside, click and hold the ChitChat window on the upper side where the taskbar is usually located, drag it anywhere. If you release the cursor, you have to get another window's focus again.

**Comment by LucaTNT** [comment] 2015-09-07 09:33
I tried tinkering around with the source code and the title bar seems to be there, but for some reason it doesn't register the clicks, it looks like they're passed to the web view that sits below it.
If I remove the web view, than I get a conveniently movable empty window. Not very useful.

Unfortunately my OS X programming skills don't go much further, so I was not able to solve the issue.

**Comment by andersio** [comment] 2015-10-01 05:47
Fixed in 1.4.

**Comment by zvaehn** [comment] 2015-10-01 08:47
awesome!

**Closed** 2015-10-05 20:38 UTC
