### ISSUE TITLE
Emojis

### ISSUE THREAD

**Issue by lemsex** [stonesam92/ChitChat#16] opened 2015-07-09 04:07 UTC
I have an issue with the emojis, as soon i start the app I Can't type emojis & i can't see if they have received my messages or they have read it. Please Help.

I love this app, is really useful but it needs to repair a few things. If i could I would help with those but i don't know how to. 

Thank You.

**Comment by Tsenuki** [comment] 2015-07-09 09:24
Actually I'm having the same problem man... Please help us!

I really love this app, every Mac user I know i tell them of this great way to have whatsapp without using firefox or chrome.

Thanks in advance.

**Comment by stonesam92** [comment] 2015-07-09 11:08
Yeah, confirmed here too.

I'll look into it, but I may not get time to make a fix until the weekend. Hopefully its just something simple like WhatsApp  changing where images are served from.

Thanks for flagging this up quickly.

**Comment by Tsenuki** [comment] 2015-07-09 11:09
No worries man! This is a great app, glad to be helpful!

**Comment by stonesam92** [comment] 2015-07-09 14:25
Found the issue.

WhatsApp Web's implementation has changed and its internals now work differently on Chrome vs Safari.

Since ChitChat was masquerading as Chrome, it was getting the incompatible Chrome-specific code rather than the Safari version.

Fixed in a15e4cd9d4ec4616eb6701d03d4c4a18f2dd98c2 and the [1.2 release](https://github.com/stonesam92/ChitChat/releases). Download the release to upgrade manually; I still need to find a workaround for name-changing auto-updates.

**Closed by stonesam92** 2015-07-09 14:25 UTC
