### ISSUE TITLE
v1.4 not working on OSX 10.11

### ISSUE THREAD

**Issue by qikkeronline** [stonesam92/ChitChat#81] opened 2015-10-01 16:16 UTC
Version 1.4 is not working on OSX 10.11 (can't connect to whatsapp web). Reverted back to 1.3 and it's working again. Can I do more to help debugging?

**Comment by roni-estein** [comment] 2015-10-01 16:17
I’m using 1.4 with no problems.

**Comment by andersio** [comment] 2015-10-02 01:00
Is the app window left blank, or is the web app loaded successfully but failed to connect to the server?

**Comment by qikkeronline** [comment] 2015-10-03 09:24
It is completely green, with the notice that it can't connect to whatsapp web and telling you to refresh - but that does not work. I can send you a screenshot of it later today :+1:

**Comment by andersio** [comment] 2015-10-03 09:51
Hmm. That would mean the app can't even load `web.whatsapp.com`. This sounds interesting, since the only change that might have caused this would be App Transport Security enforcement in 10.11 SDK, given that you can connect with v1.3. Could you try to run the following diagnostics in Terminal? Don't worry though - just a tool from Apple to test ATS compliance of a host.

```
/usr/bin/nscurl --ats-diagnostics https://web.whatsapp.com/
/usr/bin/nscurl --ats-diagnostics wss://w1.web.whatsapp.com/
/usr/bin/nscurl --ats-diagnostics https://dyn.web.whatsapp.com/
```

**Comment by qikkeronline** [comment] 2015-10-03 10:45
Everything is a pass on those tests  @andersio

**Comment by andersio** [comment] 2015-10-03 12:14
Hmm. Then I can't think of any other possible cause. Perhaps may you check if your OSX in-built firewall has blocked the latest build of ChitChat somehow?

**Comment by martinalt** [comment] 2015-10-04 09:18
Hey,
I've the same problem and have just a few details more while using the console (or what it's called in english).

See the screen below.

Thanks for the great work, would be nice to use the software soon on El Capitan.

Best,

Martin
<img width="947" alt="bildschirmfoto 2015-10-04 um 11 16 35" src="https://cloud.githubusercontent.com/assets/13983911/10267172/a6f489c8-6a89-11e5-9858-ba71be80643c.png">

**Comment by andersio** [comment] 2015-10-04 09:22
Have you tried to run the diagnostic above? It seems ATS somehow blocked `web.whatsapp.com` on your machine.

Anyway, it seems the easiest solution would be disabling ATS in ChitChat after all, hmm.

**Comment by martinalt** [comment] 2015-10-04 09:33
Yes, I did - I'm not sure if I saw everything because it was very fast, but all I saw was "PASS" for every test.

I don't know what this is, but thanks for your great and fast reply!

**Comment by andersio** [comment] 2015-10-04 09:40
I have just pushed a commit. May you please try to replace the Info.plist with this updated version, and see if the issue is resolved?
https://github.com/andersio/ChitChat/blob/c25f795ccb37e206db56d84a5cc06a92deff6a7e/WhatsMac/Info.plist

**Comment by martinalt** [comment] 2015-10-04 10:58
Thanks! I tried the info.plist with the Version 1.4 (1.4.0) without any change, sorry. Error in Konsole is still the same, I think. Screen of ChitChat looks like the attachment.
![bildschirmfoto 2015-10-04 um 12 56 59](https://cloud.githubusercontent.com/assets/13983911/10267509/91ed4a70-6a97-11e5-99aa-668a4860700f.png)

**Comment by andersio** [comment] 2015-10-04 11:01
Sorry, do you mean the Info.plist I linked? The one in the master branch of ChitChat's main repo isn't updated yet.

**Comment by martinalt** [comment] 2015-10-04 11:12
Yes, I did the changes of the edited and updated plist. Currently, my plist looks like:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>BuildMachineOSBuild</key>
	<string>14E46</string>
	<key>CFBundleDevelopmentRegion</key>
	<string>en</string>
	<key>CFBundleExecutable</key>
	<string>ChitChat</string>
	<key>CFBundleIconFile</key>
	<string>AppIcon</string>
	<key>CFBundleIdentifier</key>
	<string>com.samstone.ChitChat</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>ChitChat</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>1.4.1</string>
	<key>CFBundleSignature</key>
	<string>????</string>
	<key>CFBundleSupportedPlatforms</key>
	<array>
		<string>MacOSX</string>
	</array>
	<key>CFBundleVersion</key>
	<string>1.4.1</string>
	<key>DTCompiler</key>
	<string>com.apple.compilers.llvm.clang.1_0</string>
	<key>DTPlatformBuild</key>
	<string>7A1001</string>
	<key>DTPlatformVersion</key>
	<string>GM</string>
	<key>DTSDKBuild</key>
	<string>15A278</string>
	<key>DTSDKName</key>
	<string>macosx10.11</string>
	<key>DTXcode</key>
	<string>0701</string>
	<key>DTXcodeBuild</key>
	<string>7A1001</string>
	<key>LSMinimumSystemVersion</key>
	<string>10.10</string>
	<key>NSAppTransportSecurity</key>
    <dict>
        <key>NSExceptionDomains</key>
        <dict>
            <key>whatsapp.com</key>
            <dict>
                <key>NSThirdPartyExceptionAllowsInsecureHTTPLoads</key>
                <true/>
                <key>NSExceptionAllowsInsecureHTTPLoads</key>
                <true/>
                <key>NSIncludesSubdomains</key>
                <true/>
            </dict>
            <key>whatsapp.net</key>
            <dict>
                <key>NSThirdPartyExceptionRequiresForwardSecrecy</key>
                <false/>
                <key>NSExceptionRequiresForwardSecrecy</key>
                <false/>
                <key>NSIncludesSubdomains</key>
                <true/>
            </dict>
        </dict>
    </dict>
	<key>NSHumanReadableCopyright</key>
	<string>Mac wrapper by Sam Stone and others, available under the MIT license. Contains Code from Messenger for Mac. WhatsApp Web by WhatsApp.</string>
	<key>NSMainNibFile</key>
	<string>MainMenu</string>
	<key>NSPrincipalClass</key>
	<string>WAMApplication</string>
	<key>SUFeedURL</key>
	<string>https://raw.githubusercontent.com/stonesam92/ChitChat/master/update_appcast.xml</string>
	<key>SUPublicDSAKeyFile</key>
	<string>dsa_pub.pem</string>
</dict>
</plist>
```

**Comment by andersio** [comment] 2015-10-04 11:16
I see. May you please also try very last ATS Info.plist setting I listed? This would disable ATS completely for everything. Really appreciate your help.

**Comment by martinalt** [comment] 2015-10-04 11:24
Don't know which plist - 03fe670? The code block you commented is in the plist above. Sure, it helps us both ;)

**Comment by andersio** [comment] 2015-10-04 11:28
Just `Info.plist` but have the entire section replaced with the 5-liner. Or you can pull the Info.plist of this commit: https://github.com/andersio/ChitChat/commit/308c41e13a30e43b0992e99d311ad9cc9f5de41e

**Comment by martinalt** [comment] 2015-10-04 11:30
Thanks, I changed the lines from above the the 5 you posted and the applications works now.

**Comment by andersio** [comment] 2015-10-04 11:33
Glad to know, though I am not exactly sure about why this happened. Anyway, I will make a pull request to disable App Transport Security completely. Thanks for your help.

**Comment by andersio** [comment] 2015-10-04 11:54
The SSL connection is still there, by the way. It is just not compliant with Apple's new App Transport Security enforcements, which blocked the connections and caused the errors you might have observed in the console.

**Comment by stonesam92** [comment] 2015-10-05 19:52
App Transport Security is now disabled in 1.5, so the bug should be fixed now.

**Closed by stonesam92** 2015-10-05 19:52 UTC

**Comment by qikkeronline** [comment] 2015-10-07 10:57
Great, it's working again! Thanks! :+1:
